baseurl: /morgantown
permalink: pretty
markdown: kramdown
paginate: 5
repo: morgantown
github_org: maptime
maptime:
  chapter: MaptimeMorgantown
  twitter: MaptimeMGWV

future: true
gems:
  - jekyll-feed
