baseurl: /morgantown
permalink: pretty
markdown: kramdown
paginate: 5
repo: morgantown
github_org: maptime
maptime:
  chapter: MaptimeMorgantown
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

future: true
gems:
  - jekyll-feed
